### ISSUE TITLE
More opsec stuff...

### ISSUE THREAD

**Issue by 0x27** [JusticeRage/FFM#10]
The following presentation has a bunch of hints on stuff we should look at doing (in the same vein as the SSH processor) to prevent target-side logging of various stuff. I'll have a go myself, but I'm still stuck trying to get the thing from #9 working.

https://github.com/wvu/talks/blob/master/defcon/26/One-Liners%20to%20Rule%20Them%20All.pdf

Notably the less, wget, vim... stuff to prevent logging on the pwned box of your activities.

**Comment by JusticeRage** [comment]
Thanks a lot for that link! It indeed contains very interesting stuff that I want to add to the harness.
I'm currently a bit swamped, which explains why I haven't implemented #9 yet (sorry about that), but I'll do my best to look into all that soon!
