### ISSUE TITLE
SSH automatically adding "-T" not firing/working.

### ISSUE THREAD

**Issue by 0x27** [JusticeRage/FFM#5]
Taking the functions for a walk, noticed this... Basically I am not using the -T flag, so it should raise an alert and add it. Instead, it doesn't. Seems the regex doesn't fire or something?

```
user@box:~/FFM$ torsocks ssh -lroot [redacted]
root@[redacted]'s password: [redacted]
[redacted]
root@[redacted]:~# 
```

**Comment by JusticeRage** [comment]
Currently, `torsocks` is not recognized as a proxy command (only `torify` and a few `proxychains` variants are supported).
The harness interprets this input as a "torsocks" command and therefore doesn't apply `ssh` plugins. I will add `torsocks` to the list in the next commit (I'm currently moving said list to a configuration file). 
Generally, it's a hard problem to see what commands are actually being called. Current misses, in addition to yours, are:

- `su -c "ssh [...]"`
- `LD_PRELOAD=lib.so ssh [...]`
- `env A="test" ssh [...]`
