### ISSUE TITLE
Feature Request: Client Side Logging

### ISSUE THREAD

**Issue by 0x27** [JusticeRage/FFM#6]
It would be pretty neat to have a client-side logging functionality. I can already do this with `script`, on the client, but perhaps something baked into FFM? When freedom fighting, it might be useful to do `!log on /path/to/hacklog.txt` and `!log off` to enable/disable logging of freedom fighting activities locally.

**Comment by JusticeRage** [comment]
I've done most of the work for the logging feature. Would you be able to try it out while I work on the accompanying plugin, in case I missed a bug while testing?
Be sure to check `ffm.conf` as there are new options that control the logging behavior.
